#
# SPDX-License-Identifier: Apache-2.0
#
# Copyright 2020-2025 The JReleaser authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: JReleaser CSharp Builder

description: 'JReleaser CSharp Builder'

inputs:
  slsa-workflow-inputs:
    description: 'All the inputs'
    required: true
  slsa-layout-file:
    description: 'Location to store the layout content'
    required: true
  slsa-workflow-secret1: {}
  slsa-workflow-secret2: {}
  slsa-workflow-secret3: {}
  slsa-workflow-secret4: {}
  slsa-workflow-secret5: {}
  slsa-workflow-secret6: {}
  slsa-workflow-secret7: {}
  slsa-workflow-secret8: {}
  slsa-workflow-secret9: {}
  slsa-workflow-secret10: {}
  slsa-workflow-secret11: {}
  slsa-workflow-secret12: {}
  slsa-workflow-secret13: {}
  slsa-workflow-secret14: {}
  slsa-workflow-secret15: {}

runs:
  using: 'composite'
  steps:
    - name: Checkout branch
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v 4.2.2
      with:
        fetch-depth: 0
        ref: ${{ fromJson(inputs.slsa-workflow-inputs).branch }}

    - name: Checkout ref
      if: ${{ fromJson(inputs.slsa-workflow-inputs).tag-or-ref != '' }}
      shell: bash
      run: git checkout ${{ fromJson(inputs.slsa-workflow-inputs).tag-or-ref }}

    - name: Setup Dotnet
      uses: actions/setup-dotnet@2016bd2012dba4e32de620c46fe006a3ac9f0602 # v5.0.1
      with:
        dotnet-version: ${{ fromJson(inputs.slsa-workflow-inputs).dotnet-version }}

    - name: Assemble
      uses: jreleaser/release-action@f69e545b05f149483cecb2fb81866247992694b8 # v 2.4.2
      with:
        version: ${{ fromJson(inputs.slsa-workflow-inputs).jreleaser-version }}
        arguments: assemble
      env:
        CI: 'true'
        JRELEASER_PROJECT_VERSION: ${{ fromJson(inputs.slsa-workflow-inputs).project-version }}

    - name: JReleaser output
      if: always()
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v 4.6.2
      with:
        name: jreleaser-assemble
        path: |
          out/jreleaser/trace.log
          out/jreleaser/output.properties

    - name: Release
      uses: jreleaser/release-action@f69e545b05f149483cecb2fb81866247992694b8 # v 2.4.2
      with:
        version: ${{ fromJson(inputs.slsa-workflow-inputs).jreleaser-version }}
        arguments: release
        setup-java: false
      env:
        JRELEASER_PROJECT_VERSION: ${{ fromJson(inputs.slsa-workflow-inputs).project-version }}
        JRELEASER_GITHUB_TOKEN: ${{ inputs.slsa-workflow-secret1 }}
        JRELEASER_CATALOG_SLSA_ACTIVE: ALWAYS

    - name: JReleaser output
      if: always()
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v 4.6.2
      with:
        name: jreleaser-release
        path: |
          out/jreleaser/trace.log
          out/jreleaser/output.properties

    - name: Rename attestation file
      shell: bash
      run: |
        mv out/jreleaser/catalogs/slsa/*.intoto ${{ inputs.slsa-layout-file }}
